/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigBaseTab: typeof import('./src/components/config/base/config-base-tab.vue')['default']
    ConfigColor: typeof import('./src/components/config/config-color.vue')['default']
    ConfigColumn: typeof import('./src/components/config/config-column.vue')['default']
    ConfigFiles: typeof import('./src/components/config/config-files.vue')['default']
    ConfigInput: typeof import('./src/components/config/config-input.vue')['default']
    ConfigRichText: typeof import('./src/components/config/config-rich-text.vue')['default']
    ConfigViewport: typeof import('./src/components/config/config-viewport.vue')['default']
    EditBlockDrag: typeof import('./src/components/edit/edit-block-drag.vue')['default']
    EditConfigBlock: typeof import('./src/components/edit/edit-config-block.vue')['default']
    EditConfigPage: typeof import('./src/components/edit/edit-config-page.vue')['default']
    EditConfigRender: typeof import('./src/components/edit/edit-config-render.vue')['default']
    EditHeader: typeof import('./src/components/edit/edit-header.vue')['default']
    EditPanelBlock: typeof import('./src/components/edit/edit-panel-block.vue')['default']
    EditPanelConfig: typeof import('./src/components/edit/edit-panel-config.vue')['default']
    EditRender: typeof import('./src/components/edit/edit-render.vue')['default']
    EditRenderDrag: typeof import('./src/components/edit/edit-render-drag.vue')['default']
    EditRenderHover: typeof import('./src/components/edit/edit-render-hover.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('./src/components/base/v-icon.vue')['default']
    VSelect: typeof import('./src/components/base/v-select.vue')['default']
  }
}
